name: barcode_ml_scanner
description: Barcode scanner with Google ML
version: 0.0.1
homepage:

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: ">=2.2.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.8.1+3
  google_ml_kit:
    git:
      url: git://github.com/bharat-biradar/Google-Ml-Kit-plugin.git

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.awcoding.barcode_ml_scanner
        pluginClass: BarcodeMlScannerPlugin
      ios:
        pluginClass: BarcodeMlScannerPlugin

